-- MySQL Script generated by MySQL Workbench
-- Thu Jun  8 17:08:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema makesense
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `makesense` ;

-- -----------------------------------------------------
-- Schema makesense
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `makesense` DEFAULT CHARACTER SET utf8 ;
USE `makesense` ;

-- -----------------------------------------------------
-- Table `makesense`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `makesense`.`table1` ;

CREATE TABLE IF NOT EXISTS `makesense`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makesense`.`Job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `makesense`.`Job` ;

CREATE TABLE IF NOT EXISTS `makesense`.`Job` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makesense`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `makesense`.`Role` ;

CREATE TABLE IF NOT EXISTS `makesense`.`Role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makesense`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `makesense`.`User` ;

CREATE TABLE IF NOT EXISTS `makesense`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `avatar` LONGTEXT NULL,
  `affiliated_site` VARCHAR(45) NULL,
  `tel` VARCHAR(10) NULL,
  `Job_id` INT NOT NULL,
  `admin` TINYINT NULL,
  `Role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_User_Job1`
    FOREIGN KEY (`Job_id`)
    REFERENCES `makesense`.`Job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_id`)
    REFERENCES `makesense`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_User_Job1_idx` ON `makesense`.`User` (`Job_id` ASC) VISIBLE;

CREATE INDEX `fk_User_Role1_idx` ON `makesense`.`User` (`Role_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `makesense`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `makesense`.`Post` ;

CREATE TABLE IF NOT EXISTS `makesense`.`Post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(100) NULL,
  `description` LONGTEXT NULL,
  `date` DATE NULL,
  `status` VARCHAR(45) NULL,
  `profit` LONGTEXT NULL,
  `risk` LONGTEXT NULL,
  `avatar` LONGTEXT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Post_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `makesense`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Post_User1_idx` ON `makesense`.`Post` (`User_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `makesense`.`User_Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `makesense`.`User_Post` ;

CREATE TABLE IF NOT EXISTS `makesense`.`User_Post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Users_id` INT NOT NULL,
  `Posts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Users_Posts_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `makesense`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_Posts_Posts1`
    FOREIGN KEY (`Posts_id`)
    REFERENCES `makesense`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Users_Posts_Users1_idx` ON `makesense`.`User_Post` (`Users_id` ASC) VISIBLE;

CREATE INDEX `fk_Users_Posts_Posts1_idx` ON `makesense`.`User_Post` (`Posts_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `makesense`.`User_Post_Avis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `makesense`.`User_Post_Avis` ;

CREATE TABLE IF NOT EXISTS `makesense`.`User_Post_Avis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `Post_id` INT NOT NULL,
  `text` LONGTEXT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Users_Posts_Avis_Users1`
    FOREIGN KEY (`User_id`)
    REFERENCES `makesense`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_Posts_Avis_Posts1`
    FOREIGN KEY (`Post_id`)
    REFERENCES `makesense`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Users_Posts_Avis_Users1_idx` ON `makesense`.`User_Post_Avis` (`User_id` ASC) VISIBLE;

CREATE INDEX `fk_Users_Posts_Avis_Posts1_idx` ON `makesense`.`User_Post_Avis` (`Post_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `makesense`.`User_Participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `makesense`.`User_Participant` ;

CREATE TABLE IF NOT EXISTS `makesense`.`User_Participant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `User_id` INT NOT NULL,
  `Post_id` INT NOT NULL,
  `expert` TINYINT NULL,
  `impacted` TINYINT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_impacted_Users1`
    FOREIGN KEY (`User_id`)
    REFERENCES `makesense`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Impacted_Post1`
    FOREIGN KEY (`Post_id`)
    REFERENCES `makesense`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_impacted_Users1_idx` ON `makesense`.`User_Participant` (`User_id` ASC) VISIBLE;

CREATE INDEX `fk_User_Impacted_Post1_idx` ON `makesense`.`User_Participant` (`Post_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `makesense`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `makesense`.`Tag` ;

CREATE TABLE IF NOT EXISTS `makesense`.`Tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makesense`.`Post_Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `makesense`.`Post_Tag` ;

CREATE TABLE IF NOT EXISTS `makesense`.`Post_Tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Post_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_posts_tags_Posts1`
    FOREIGN KEY (`Post_id`)
    REFERENCES `makesense`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_tags_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `makesense`.`Tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_posts_tags_Posts1_idx` ON `makesense`.`Post_Tag` (`Post_id` ASC) VISIBLE;

CREATE INDEX `fk_posts_tags_tag1_idx` ON `makesense`.`Post_Tag` (`tag_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `makesense`.`Alert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `makesense`.`Alert` ;

CREATE TABLE IF NOT EXISTS `makesense`.`Alert` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `text` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makesense`.`User_Alert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `makesense`.`User_Alert` ;

CREATE TABLE IF NOT EXISTS `makesense`.`User_Alert` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Alert_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_User_Alert_Alert1`
    FOREIGN KEY (`Alert_id`)
    REFERENCES `makesense`.`Alert` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Alert_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `makesense`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_User_Alert_Alert1_idx` ON `makesense`.`User_Alert` (`Alert_id` ASC) VISIBLE;

CREATE INDEX `fk_User_Alert_User1_idx` ON `makesense`.`User_Alert` (`User_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
